### ISSUE TITLE
Backbuffer inverted problem

### ISSUE THREAD

**Issue by fekga** [markusfisch/ShaderEditor#1]
Hi!

I know this project was updated about a year ago but I wanted to inform you about the issue with the backbuffer variable. The result texture in the shader gets flipped on the x-axis.

**Comment by markusfisch** [comment]
Hi, first of all, thanks for posting this issue. The project is still alive!

Wasn't aware of the flipping and will definitely look into it.

**Comment by markusfisch** [comment]
Hi fekga,

is it possible, you're not using uv coordinates (from 0 to 1) to access the backbuffer texture?

This is how I use the backbuffer texture:

	vec2 uv = gl_FragCoord.xy/resolution.xy;
	color = texture2D( backbuffer, uv ).rgb;

Try that shader for example:

	precision mediump float;

	uniform float time;
	uniform vec2 resolution;
	uniform sampler2D backbuffer;

	void main( void )
	{
		vec2 uv = gl_FragCoord.xy/resolution.xy;
		vec2 p = gl_FragCoord.xy/min(
			resolution.x,
			resolution.y );

		vec3 color = vec3( smoothstep( .21, .2,
			distance(
				p,
				vec2( .6, .5+sin( time*.5 )*.2 ) ) ) );

		color = mix(
			color,
			texture2D( backbuffer, uv ).rgb,
			.9 );

		gl_FragColor = vec4( color, 1.0 );
	}

Does it work for you?

I tried quite a lot different devices but wasn't able to reproduce the problem at first. Then I used gl_FragCoord.xy to access the backbuffer texture which sort of produced a x-flipped image somehow. Although that shouldn't happen because the texture wrap is set to CLAMP_TO_EDGE which means out-of-bound values should get the value of the corresponding edge.

But in the process I stumbled upon a really nasty bug: if a shader uses the backbuffer, it renders upside down!

So yes, indeed, there's a flipping but on the y axis. And it was quite tough nut to crack. Long story short, I rendered in the frame buffer holding the backbuffer texture first and then to the screen. It seems that, because textures have their origins in the bottom left, rendering into a texture does automatically apply a transformation which does not get restored when you choose frame buffer 0 to render to the screen. Rendering to the screen first and then into the texture did fix the problem.

I just posted an update to Google Play and Shader Editor 1.6 is the latest version now.

**Comment by fekga** [comment]
It does work now,thanks for the fix and the other uniform variables!

Another problem I encountered today:
When compile on change is disabled and you edit the code without compiling,
switch to the view mode and compile the shader which has syntax errors,
then the bug icon appears but you won't be able to switch back to editor
view without using another shader.

**Comment by markusfisch** [comment]
Oh, I see. Just pushed a fix on GitHub and posted an update to Google Play. Should be available within the next few hours.

Thanks for the bug report!

**Comment by nathanross49** [comment]
Thank you for this fix. I also noticed that gl_FragCoord.y was inverted and am glad to see it fixed.
