### ISSUE TITLE
Import & export feature not available

### ISSUE THREAD

**Issue by Maurdekye** [markusfisch/ShaderEditor#104]
I distinctly remember there used to be a feature for importing & exporting shaders from the app, but it appears to be missing somehow. I just got a new phone, and I'd like to be able to transfer my shaders on to it from my old one, but I can't figure out how.

**Comment by Maurdekye** [comment]
After browsing through the code, I came across this commit that explicitly removes the feature; 

5f747493f364d3952a53110e7bc1e01a510d9a26

Supposedly due to some incompatibility with the changes to app storage in API version 29. Is there any chance of seeing this feature returned in some form? It really sucks having my shaders stuck on my old phone, and it'd be a pain to have to copy them over one by one manually.

**Comment by markusfisch** [comment]
Well, sorry, this is quite unfortunate. Because of Android O's new Scoped storage model, it's impossible to read a directory from the sdcard without very special permissions (meant to be used for file browsing apps). This is why the existing code doesn't work anymore on Android O.

Now, there should be a replacement, of course, and I already have an idea for that. Instead of exporting a number of files, the app could simply export (and import) the Sqlite database. I already do this in other apps so I hope it will be quite easy to add this feature.

**Comment by Maurdekye** [comment]
Glad to hear, although it does make my life a bit harder. I'm currently in the process of manually copying each shader over one by one using Nearby Share. Tedious for sure, but a solution nonetheless.

**Comment by markusfisch** [comment]
Even though it probably won't help anymore: Version [2.22.0](https://github.com/markusfisch/ShaderEditor/releases/tag/2.22.0) can now export the whole SQLite database and import it back again.

It's currently in beta on Google Play and will become available within the next few hours. F-Droid should update by tomorrow.

Sorry again for the trouble.
