### ISSUE TITLE
FAQ menu item does nothing (f-droid) 

### ISSUE THREAD

**Issue by lewiji** [markusfisch/ShaderEditor#109]
I have just installed version 2.23.1 from f-droid for the first time on my device. Tapping "FAQ" in the drop down menu appears to do nothing, the menu just closes. 

Of course, I just came here and found the FAQ that way :)

Let me know if there's a way I can dig out more info if you can't replicate (adb?) 

Samsung S21 Ultra
Android 12 (November 2021 patch level)

**Comment by markusfisch** [comment]
Good catch! And thanks for filing an issue! 👍 

This is a bug 🙈 Because of the new package visibility restrictions in API level 30+, we can no longer use `resolveActivity()` to check if we can run `startActivity()` with a given `Intent` (in this case opening a URL). Instead, we should simply try and catch the `ActivityNotFoundException`.

Solved in https://github.com/markusfisch/ShaderEditor/commit/3068fd4f73555bdfb01512019efae2698f7ddc5b

Thanks again for contributing! 😄 There will be an update in the next few hours.
