### ISSUE TITLE
Problem with loops

### ISSUE THREAD

**Issue by yesimwearingpants** [markusfisch/ShaderEditor#11]
I am trying to alternate colors so I used this loop 
float j;
do {
if(j==.8){
//b for blue
b = uv.y+j;
j -= .1;
} else if ( j== .4){
b = uv.y+j;
j -= .1;
} j=.4;
} while (j!=1.0);

It freezes and crashes on compile. I wanted to use
 ctime for a delay but is there a better way I 
should be doing this, I an Very new too OpenGL

**Comment by markusfisch** [comment]
I'm sorry, I don't quite understand what you're trying to do. If you're simply trying to alternate colors, it's better to use math instead of conditional statements.

Something like:

	gl_FragColor = vec4(
		sin( time*0.2 ),
		sin( time*0.3 ),
		sin( time*0.4 ),
		1.0 );

Please have a look at the [GLSL documentation](https://www.opengl.org/documentation/glsl/) and check out a few simple shaders from [here](https://www.shadertoy.com/) or [here](http://glslsandbox.com/).
