### ISSUE TITLE
Lowering framerate when in battery saver mode

### ISSUE THREAD

**Issue by stuartpb** [markusfisch/ShaderEditor#12]
It's kind of disconcerting that in Battery Saver, where all animations are disabled, Android does nothing to limit live wallpapers, so my Shader Editor live wallpaper keeps scrolling at a buttery-smooth 60fps.

It'd be better if, when in Battery Saver, Shader Editor lowered the framerate to at most 1 FPS.

**Comment by markusfisch** [comment]
Interesting idea. Put it on the feature list.

Although, since the live wallpaper is only running (and therefore consuming energy) when you see it, I wouldn't expect too much from lowering the frame rate in battery saver mode.

Maybe, it would also be an option, to just show solid black in battery saver mode so OLEDs would save even more energy.

**Comment by stuartpb** [comment]
> Maybe, it would also be an option, to just show solid black in battery saver mode so OLEDs would save even more energy.

I think this is really the behavior that should be implemented, considering the way everything else degrades in battery saver mode.

**Comment by markusfisch** [comment]
Landed in master.
