### ISSUE TITLE
Feature Request: Tab key support

### ISSUE THREAD

**Issue by domportera** [markusfisch/ShaderEditor#127]
Some keyboards (such as AnySoftKeyboard) support a Tab key. In a text editor I would expect this key to indent/outdent, but in this application it just navigates the greater UI. Would make touchscreen coding much nicer.

PS thank you for this amazingly fun application :^) I've been using it for a loong time now and I expect to for a long time more

**Comment by markusfisch** [comment]
Good point! 👍 I wasn't aware of soft keyboards that have real tab keys, and AnySoftKeyboard really looks very nice! Thanks for the tip!

So I've added a setting (which is set by default) to make the tab key add indent instead of being used for focus navigation.

A new version 2.28.0 is on its way through Google Play and should become available in the next few hours. You can also get it directly from GitHub if you want:
https://github.com/markusfisch/ShaderEditor/releases/tag/2.28.0

Thanks for making the app better! 😄

**Comment by domportera** [comment]
amazing! no, thank YOU! :)
