### ISSUE TITLE
Adding a texture in sampler 2D and using it in a shader crashes the app

### ISSUE THREAD

**Issue by kStor2poche** [markusfisch/ShaderEditor#133]
# Description
I tried to add Tame Impala 's currents album cover as a 1024x1024 texture in Sampler2D named currents and while that works, putting `uniform sampler2D noise;` in my shader crashes the app. 

The first time it happened, it wasn't too bad because the editor reverted to an older version of the file, but when I tried again, it seemed to have saved the file and trying to load it crashes the app.

Here's the particular image I used
![cover_.jpg](https://user-images.githubusercontent.com/43518872/218579478-17ae3e8c-4d8b-4329-9688-8616d55a6b68.jpg)

I tried to export the database, edit or even delete the shader in the database then import it back, but nothing changed . Though I could get a similar code and modify it to get back my shader in a way, there's currently no way I have found to get the crashing shader modified or deleted.

**Comment by markusfisch** [comment]
Sorry for this 🙈 The reason is that this texture is too large - at a size of 1024x1024 - to fit into a `CursorWindow` 😬 

I just fixed the crash in https://github.com/markusfisch/ShaderEditor/commit/5d4875f5ebe5cebb3cf47d1d2d6970a452c8edd7 and uploaded a new version, 2.28.2, to Google Play. It should become available within the next few hours, or you can get it directly from GitHub here:
https://github.com/markusfisch/ShaderEditor/releases/tag/2.28.2

This new version will automatically remove too large textures when you click on them in the list of textures to keep the app working. So you will need to import this image again, preferably at a smaller size.

**Comment by kStor2poche** [comment]
Great, thank you very much for the quick fix ! 👍
