### ISSUE TITLE
Feature Request: Lexer-/Parser-Based Syntax highlighting

### ISSUE THREAD

**Issue by AntonPieper** [markusfisch/ShaderEditor#140]
I think migrating to [treesitter](https://tree-sitter.github.io/tree-sitter/) (Maybe using a modified [Java implementation](https://github.com/serenadeai/java-tree-sitter)? Would need to modify the `Languages` class and `build.py` to support GLSL though) based syntax highlighting could be worthwhile.

Reasons:
 1. It is fast for big files
 2. It potentially supports changes in source code without recreating all the spans
 3. Potential for future semantic highlighting / analysis for autocompletion

**Comment by markusfisch** [comment]
Treesitter looks really interesting! I'll give it a try for sure! Since fragment shaders are usually quite short (of course I know this is not always the case 😉), the current solution is/was good enough for most cases. But it sure has it's shortcomings, and that the editor is getting slower when the code gets bigger has plagued this app for while now.Am 14.06.2023 10:55 schrieb Anton Pieper ***@***.***>:
I think migrating to treesitter (Maybe using a modified Java implementation? Would need to modify the Languages class and build.py to support GLSL though) based syntax highlighting could be worthwhile.
Reasons:
It is fast for big filesIt potentially supports changes in source code without recreating all the spansPotential for future semantic highlighting / analysis for autocompletion

**Comment by AntonPieper** [comment]
The Java implementation is flawed IMO, but there also is [android-tree-sitter](https://github.com/AndroidIDEOfficial/android-tree-sitter), which is a simple dependency for Gradle. This is already used in their IDE [AndroidIDE](https://github.com/AndroidIDEOfficial/AndroidIDE) to highlight XML and Java. They (obviously) don't have GLSL grammar, but this might be a simple task as the developer kindly [outlined the steps in an issue I opened](https://github.com/AndroidIDEOfficial/android-tree-sitter/issues/20#issuecomment-1593679412). Having tried a simple example using the Java grammar ([`com.itsaky.androidide:tree-sitter-java:3.0.1`](https://github.com/AndroidIDEOfficial/tree-sitter-java)), it seems to "just work". There also already is an official (at least linked on the [official site](https://tree-sitter.github.io/tree-sitter/#parsers)) grammar for GLSL: [theHamsta/tree-sitter-glsl](https://github.com/theHamsta/tree-sitter-glsl).

**Comment by AntonPieper** [comment]
Hello again!

I think I have now implemented a syntax highlighting solution that works quite fast. The lag now comes from the EditText and not the (separate) SyntaxEditor View. I have also moved the line numbers into its own view, however this has one side effect: when the EditText changes size vertically (i.e. a new line), the phone scrolls to put the cursor at the far left of the screen. I will look into `MovementMethod` to see if this can be fixed. Maybe this is not that big of a problem? Also I have increased the API level temporarily to use `android/trace, this will be reverted. Of course I will open several pull requests for the various changes. You can look at the changed version here: [c-highlight branch](https://github.com/AntonPieper/ShaderEditor/tree/c-highlight)
