### ISSUE TITLE
QoL: Hide TAB button when code is hidden

### ISSUE THREAD

**Issue by Martysh12** [markusfisch/ShaderEditor#142]
## Problem
I toggle code a lot, but every once in a while instead of going back I hit the TAB button accidentally.
This leaves annoying whitespace wherever the cursor was when you pressed Toggle Code that is hard to track down sometimes, because the cursor is hidden once you open the editor again.

## Solution
When you press the Toggle Code button, the TAB button should be hidden as well.

**Comment by markusfisch** [comment]
Thanks for the suggestion! I can totally see why this is annoying! Fortunately, it's easy to fix! Implemented in https://github.com/markusfisch/ShaderEditor/commit/e40628f2d627375610f955e3b95c5c57aeb6e66a

Please note that this fix only disables the Tab menu item while the code is hidden, instead of hiding it, because hiding the Tab menu item would make all following menu items change position (on screen).

Will be in the next release.
