### ISSUE TITLE
Shader gets jagged with time

### ISSUE THREAD

**Issue by rafaellago** [markusfisch/ShaderEditor#19]
Shader starts running just fine, but it gets losing definition, to get really pixelated and ugly. I don't know if its a problem with how my graphics chip deals with the repetitions, or my shader code is problematic. My phone is a Xperia Z3 Compact. And attached are the images of how its looking, less than 30 sec between one image and another.

![screenshot_2015-12-07-16-38-01](https://cloud.githubusercontent.com/assets/7526047/11636112/9163b89a-9d01-11e5-83ac-8cabce1972ab.png)
![screenshot_2015-12-07-16-38-28](https://cloud.githubusercontent.com/assets/7526047/11636111/91616d7e-9d01-11e5-81f3-4f3edb9ac6c4.png)

**Comment by markusfisch** [comment]
I suppose it's because the value of the time uniform (which is a float, probably with mediump precision?) gets too big. There is already an issue about that: https://github.com/markusfisch/ShaderEditor/issues/14

Two solutions, either you try to get a higher precision by putting the following before your code:

```glsl
#ifdef GL_FRAGMENT_PRECISION_HIGH
precision highp float;
#else
precision mediump float;
#endif
```

Or try the beta of the upcoming, new version:

https://play.google.com/apps/testing/de.markusfisch.android.shadereditor

This version wraps the time value at 60000 to avoid too big numbers. When a float gets too big, there can big quite big [rounding errors](http://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html#680).

**Comment by rafaellago** [comment]
Tried the highp approach, with no luck. Then downloaded the beta. And now it's super smooth. Thank you! I'll honor this beta invitation, and let you know about any other issues I may find. Great app!
