### ISSUE TITLE
still the backbuffer

### ISSUE THREAD

**Issue by fekga** [markusfisch/ShaderEditor#3]
Hi again!

I tried some little code out that uses the backbuffer and the result image started "swimming" away to the top right direction. So I tried to compensate the movement by adding values to the 2nd parameter of texture2D. It seems the value of +vec2(0.001) solved this.
I hope I'm using the function correctly, by writing:
texture2D(backbuffer,gl_FragCoord.xy/resolution.xy+vec2(0.001))

**Comment by markusfisch** [comment]
Hi,

yes, you're using texture2D() correctly. But unfortunately, I don't know what may cause the swimming yet. May be it's a precision issue? Does your shader start with

	precision mediump float;

Do you see the effect with the test shader I posted before too?
If not, could you please try to isolate the issue in a demo?

**Comment by fekga** [comment]
I wrote a demo with a simple circle and a time indicator on the side to
show the problem:

precision mediump float;

uniform float time;
uniform vec2 resolution;
uniform sampler2D backbuffer;

void main( void )
{
vec2 uv = gl_FragCoord.xy/resolution.xy;
vec2 p = -1.0+2.0*uv;
p.x *= resolution.x/resolution.y;

vec3 col = vec3(1.0);
vec3 bb;
float t = mod(time,12.0);
if(t < 4.0)
    bb = texture2D(backbuffer,uv).rgb;
  else if(t < 8.0)
    bb = texture2D(backbuffer,uv+0.001).rgb;
  else if(t < 12.0)
    bb = texture2D(backbuffer,uv-0.001).rgb;

  col *= smoothstep(0.5,0.51,length(p));

  col = mix(col,bb,0.95);

  if(uv.x <0.01 && uv.y < t/12.0)
  col = vec3(1.0,0.0,0.0);

gl_FragColor = vec4( col, 1.0 );
}

There are 3 states, in the first without offset, the second one has the
offset that fixed the swimming and a negative offset to double the effect.
I have an Xperia Z1 Compact with latest possible updates if that helps you
solve this issue.

**Comment by markusfisch** [comment]
Sorry for the late answer; I was quite busy this week. And thanks for making a demo shader. That helped a lot.

Now, after investigating the problem, a few miles down the rabbit hole, I found my first stab to be just right :) It's a precision issue. If you start your shader with

	precision highp float;

and therefore 24 bits of precision, the effect should vanish.

__mediump__ does only have 11 bits of precision which apparently isn't enough for the (high-dpi) resolution of your device.

Please note, that __highp__ isn't available on many older (or mdpi) devices so your shader won't run everywhere.

PS:
Just because of the branching in the demo shader; you shouldn't use __if__ statements in shaders (that much). See __Use Branching Instructions with Caution__ in [Best Practices for Shaders](https://developer.apple.com/library/ios/documentation/3DDrawing/Conceptual/OpenGLES_ProgrammingGuide/BestPracticesforShaders/BestPracticesforShaders.html).
