### ISSUE TITLE
Option "set as wallpaper"

### ISSUE THREAD

**Issue by plumpudding** [markusfisch/ShaderEditor#36]
I very much like your work, a way to donate something would be great!

An option to set the shader one is currently editing or viewing as wallpaper would be great.

**Comment by markusfisch** [comment]
Well, unfortunately Android doesn't allow setting a live wallpaper from an app. We can only open the wallpaper chooser - would this be an option?

If you just want to update (an already set) wallpaper shader, there's a menu item "Update wallpaper" (what's only visible if the current wallpaper is the wallpaper).

**Comment by plumpudding** [comment]
The "Update Wallpaper" option is only available for the shader that is selected for use in the live wallpaper.

**Comment by markusfisch** [comment]
Added in https://github.com/markusfisch/ShaderEditor/commit/e7c44b1da1344097e6d80487364bb8889fac648b. If the current shader is used for the live wallpaper, the menu item (still) says "Update wallpaper", otherwise it will read "Set as wallpaper" and will select the current shader as live wallpaper.

Published in beta, Version 2.4.6 (should become available within the next hour or so):
https://play.google.com/apps/testing/de.markusfisch.android.shadereditor
