### ISSUE TITLE
Load Syntax Highlighting Colours from XML 

### ISSUE THREAD

**Issue by TheDiamondYT1** [markusfisch/ShaderEditor#50]
**Wow, what a great app!**

[I am making an IDE](https://github.com/TheDiamondYT1/ModPEStudio) and i have used your syntax highlighting code but modified it quite alot. Some changes i've made that you could incorporate into ShaderEditor:

* **Loading words to highlight and the colours to highlight them**  
As you can see [in this java file](https://github.com/TheDiamondYT1/ModPEStudio/blob/master/app/src/main/java/tk/thediamondyt/modpeide/widget/CodeEditor.java#L87) i have loaded an [xml file](https://github.com/TheDiamondYT1/ModPEStudio/blob/master/app/src/main/assets/default.xml).  
    [Now here's where the magic happens](https://github.com/TheDiamondYT1/ModPEStudio/blob/master/app/src/main/java/tk/thediamondyt/modpeide/widget/CodeEditor.java#L115). No additional libraries needed. This also allows for custom themes.    
  
* **Scrapping the runnable**  
Im not sure if this is possible in your case, but i scrapped the runnable and update handler for a simple `setHighlighted` method in the `onDraw` method. Its super fast.   
  
---

I hope you take my ideas into consideration! \<3

**Comment by TheDiamondYT1** [comment]
Also, users could just add custom values to the xml file so that more words can be highlighted.

**Comment by markusfisch** [comment]
Thanks for sharing the idea! Your app looks quite promising too!

It's nice to be able to control highlighting by simply adding XML nodes for a pattern. But if you do that for literals, it also means a lot redundancy because one particular color (for a highlighting class, say for keywords or numbers or strings) is specified many times. So I would rather specify a regex pattern (like in those [constants](https://github.com/markusfisch/ShaderEditor/blob/master/app/src/main/java/de/markusfisch/android/shadereditor/widget/ShaderEditor.java#L41)) in the XML file. Looking at your code I saw you had problems with regex patterns in XML - did you escape all characters that aren't allowed in XML?

And I would prefer to run Pattern.compile() only once, up front, and save those patterns instead of the DOM elements. Compiling a regex pattern may take some time and the faster a highlighting run is, the better.

Speaking about speed, please note that managing many [Spannable](https://developer.android.com/reference/android/text/Spannable.html)'s can become a bottle neck for larger sources (> ~500 LOC), see https://github.com/markusfisch/ShaderEditor/issues/31. I don't know if that is a potential problem for your app (?).

PS:
Reading your code, I saw you are saving the latest MainActivity object in a static variable [here](https://github.com/TheDiamondYT1/ModPEStudio/blob/master/app/src/main/java/tk/thediamondyt/modpeide/MainActivity.java#L18) to give it to [Utils.error()](https://github.com/TheDiamondYT1/ModPEStudio/blob/master/app/src/main/java/tk/thediamondyt/modpeide/widget/CodeEditor.java#L96). Saving a context (other than the application context) or anything that is tied to a context (Views, etc.) is bad because it results in a memory leak (not in your case but nonetheless). Instead, use [View.getContext()](https://developer.android.com/reference/android/view/View.html#getContext()) to get the context inside a view.

By the way, just because I stumbled over it, the reason Replace is crashing is that you're using Activity.findViewById() to find a view in the dialog. You should cast `dialog` and invoke findViewById() on that like this:
```java
String replace = ((EditText) ((AlertDialog) dialog).findViewById(R.id.replaceText)).getText().toString();
```

**Comment by TheDiamondYT1** [comment]
@markusfisch Thanks for the fix, i made that stupid mistake awhile ago in another app i was making
