### ISSUE TITLE
Accuracy problem with gl_FragCoord.y

### ISSUE THREAD

**Issue by GbBrou** [markusfisch/ShaderEditor#55]
I have found a problem with the accuracy of `gl_FragCoord.y`.

Here is a shader to visually see the problem:
```
#ifdef GL_FRAGMENT_PRECISION
precision highp float;
#else
precision mediump float;
#endif

uniform float time;
uniform vec2 resolution;

void main( void )
{
  if(floor(gl_FragCoord.y) == mod(floor(time*2.0), resolution.y))
    gl_FragColor = vec4(1.0);
}
```
This shader is suppose to simply light up one row at a time based on the timer.
On my device (Moto G 2015), the line sometime disappear or even, sometime two rows are light up.
This problem doesn't occur with `gl_FragCoord.x`, which is working correctly.
I tested on another device (Alcatel One Touch Fierce 2) and the problem still persists.

I tested an equivalent of the previous shader on [http://editor.thebookofshaders.com/](url) and everything seems fine:
```
#ifdef GL_ES
precision mediump float;
#endif

uniform float u_time;
uniform vec2 u_resolution;

void main( void )
{
  if(floor(gl_FragCoord.y) == mod(floor(u_time*2.0), u_resolution.y))
    gl_FragColor = vec4(1.0);
}
```

There is definitely something wrong with `gl_FragCoord.y` in ShaderEditor and I guess it should be solved ASAP since it affect all shaders.

**Comment by markusfisch** [comment]
That's probably just another incarnation of the [famous](https://github.com/markusfisch/ShaderEditor/issues/10#issuecomment-160463706) floating point [rounding error](http://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html#680).

The effect you're seeing is presumably a result from rounding errors at `time*2.0`. `time` is a float holding the seconds (including the subsecond part as a fraction) since the start of rendering. Because of the way computers save floating point numbers, that float cannot hold all possible values so it's off by a fraction every now and then.

We might not see the exact same behavior on [editor.thebookofshaders.com](http://editor.thebookofshaders.com/) because the rendering surface has different dimensions and so `u_time*2.0` might be less often off, incidentally.

By the way, [gl_FragCoord](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/gl_FragCoord.xhtml) is set by OpenGL, not by the app.
