### ISSUE TITLE
Video Camera

### ISSUE THREAD

**Issue by stefnotch** [markusfisch/ShaderEditor#60]
It would be pretty cool if the camera's video stream could be accessed with a texture.

**Comment by markusfisch** [comment]
That's quite some time on my list now and I've got all the bits and pieces laying around already :) I really need to allocate some time to get this done ...

**Comment by rafaellago** [comment]
About time... I'm trying to find some time, and try to download and build your code from source. And try to help you close some issues. I really like your project!

**Comment by markusfisch** [comment]
That would be great! There are quite some issues I'd really like to close but don't have the time right now.

**Comment by markusfisch** [comment]
Well, turns out it's really quite ugly to pull this off ...

I've implemented it in https://github.com/markusfisch/ShaderEditor/tree/cam

But beware, it only works in the MainActivity (preview behind code editor); the PreviewActivity and live wallpaper will crash if you access the new `camera` texture. It's just a prototype.

What's really ugly is that we can't get the camera feed without a SurfaceView (that shows the camera feed) somewhere in the view hierarchy. This is because of security. It should keep apps from spying without the user knowing. Except it doesn't ... because a 1x1 SurfaceView is enough and that's just what I did here. So it's a hack. What Google may probably fix in the future ...

Also, working with the support RenderScript library is probably problematic. Lint is throwing a `GradleCompatible` error because the library seems to have a different version scheme than everything else. Downgrading all support libraries to the latest renderscript library didn't help. So it may or may not crash on certain devices.

**Comment by stefnotch** [comment]
Note: I don't really know anything about Android apps.


"..that we can't get the camera feed without a SurfaceView" Then, how do camera filter apps do it? E.g.
https://github.com/nekocode/CameraFilter
https://github.com/nekocode/CameraFilter/search?utf8=✓&q=surface&type=

**Comment by markusfisch** [comment]
Oh my ... you're right. Somehow I totally missed [Camera.setPreviewTexture()](https://developer.android.com/reference/android/hardware/Camera.html#setPreviewTexture(android.graphics.SurfaceTexture)) 🙈 

[SurfaceTexture](https://developer.android.com/reference/android/graphics/SurfaceTexture.html) is exactly what we need ... and I think we don't even need RenderScript either.

Thanks a bunch for pushing me into the right direction!

**Comment by markusfisch** [comment]
Implemented in https://github.com/markusfisch/ShaderEditor/commit/6b69399704b721a768d8e803e9fb4d4df96ae72f
