### ISSUE TITLE
Can't set live wallpaper

### ISSUE THREAD

**Issue by ptrsr** [markusfisch/ShaderEditor#72]
Hi,

Lovely app but I am unable to set a live wallpaper. Nothing happens when I select the button.
I'm running android 7.0 on a LG V20.

Let me know if I can help solve the issue in any way.

**Comment by markusfisch** [comment]
Hi, do you mean the menu item in the app? You need to set the app as live wallpaper using the system settings first (Settings > Display > Wallpaper > Live Wallpaper). As soon as the app is set as live wallpaper, the menu item in the app will update the shader running in the live wallpaper. Sorry for the confusion.Am 30.12.2017 01:40 schrieb Ruud Peters <notifications@github.com>:Hi,
Lovely app but I am unable to set a live wallpaper. Nothing happens when I select the button.
I'm running android 7.0 on a LG V20.
Let me know if I can help solve the issue in any way.

**Comment by ptrsr** [comment]
interesting, apperently I cannot set a live wallpaper through the settings menu (since the option is missing there). But if I press and hold on any homescreen I can. Guess this differers on different android versions.

**Comment by ptrsr** [comment]
interesting, apperently I cannot set a live wallpaper through the settings menu (since the option is missing there). But if I press and hold on any homescreen I can. Guess this differers on different android versions.
