### ISSUE TITLE
Shader version mismatch when trying to use OpenGL ES 3.0

### ISSUE THREAD

**Issue by Tynach** [markusfisch/ShaderEditor#73]
I was wanting to use functions like `inverse()`, but it seems the app doesn't support setting the version to '300 es'. Perhaps an option somewhere should be added so that we can choose which version of OpenGL we use?

**Comment by markusfisch** [comment]
Ah, that's because the app is still using [GLES20](https://developer.android.com/reference/android/opengl/GLES20.html) to support API levels below 18 (Android 4.3) what's the minimum for [GLES30](https://developer.android.com/reference/android/opengl/GLES30.html).

Since there are probably not that many devices left running Android 4.3 or older, I will probably change this in 2018 and migrate to a more up to date [minSdkVersion](https://github.com/markusfisch/ShaderEditor/blob/master/app/build.gradle#L14).

**Comment by markusfisch** [comment]
I've read it up and it should be possible to choose an GLES 3.0 context even when the app does use the GLES20 interface (if GLES 3.0 is available on the device). So, if you want to try, please check out the latest beta version which you can access here:

https://play.google.com/apps/testing/de.markusfisch.android.shadereditor

Of course, some GLES 3.0 features are incompatible with GLES 2.0 so please report any problems you may find.

**Comment by Tynach** [comment]
Theory: if there are two shaders being used - the user-defined one, and another - perhaps they *both* need to be the same version? Maybe it's the vertex shader, for example?

**Comment by markusfisch** [comment]
You're right! From section 3.4 of the [docs](https://www.khronos.org/registry/OpenGL/specs/es/3.0/GLSL_ES_Specification_3.00.pdf):

> Shaders declaring version 3.00 of the shading language cannot be linked with shaders declaring version 1.00.

So I matched the version declaration of the vertex shader with the fragment shader and it's working now! 😄

I've just submitted a new beta, it's version 2.10.1. Should be available in a few minutes.

**Comment by Tynach** [comment]
It works like a charm! There were some weird errors with a few preprocessor directives, but they were things I hadn't tried on my phone before and they were easy to fix by changing up a bit of the syntax. I have a feeling that'd be dependent on driver implementations.

**Comment by markusfisch** [comment]
Great! 😄 

And yes, I've experienced some differences in driver implementations as well.
