### ISSUE TITLE
version 320 es error

### ISSUE THREAD

**Issue by Sashasan** [markusfisch/ShaderEditor#94]
L0001 Shader languages do not match #version 320 es

**Comment by markusfisch** [comment]
Fixed in https://github.com/markusfisch/ShaderEditor/commit/ddad9bf156035b9593335661ae82fd78ec3d5a32

Version 2.18.0 will become available shortly in the beta channel. You can opt-in here to try it:

https://play.google.com/apps/testing/de.markusfisch.android.shadereditor

You can always opt-out and go back to the production version. Alternatively you may install the APK directly from here:

https://github.com/markusfisch/ShaderEditor/releases
