### ISSUE TITLE
Improve horizontal scrolling

### ISSUE THREAD

**Issue by AaronRecord** [markusfisch/ShaderEditor#96]
I've had a lot of trouble with scrolling horizontally in the text editor (see the gif)

![20200711_091718](https://user-images.githubusercontent.com/50304111/87227330-8807b900-c357-11ea-9bfd-451a6dde77d7.gif)

**Comment by Mehran7kl** [comment]
in my phone. when i start a new line it moves editor to the nex page and right aligned

**Comment by Kwauhn** [comment]
I would like to second this, and also elaborate on the issue:

Horizontal scrolling only works when vertical finger movement is below a _very_ low threshold. For every tap + hold, any vertical finger movement above this threshold locks the scrolling to vertical only. Reducing vertical finger movement to below this threshold after vertical scrolling is locked and then continuing to move your finger horizontally does **not** unlock vertical scrolling.

This creates a situation where you tap + hold, move your finger horizontally to initiate horizontal scrolling, accidentally move your finger a little too much vertically, and the scrolling direction gets locked to vertical which forces you to remove your finger and place it back down in order to resume scrolling horizontally.

My suggestion is to...
1. make the threshold to initiate scrolling equal for both horizontal and vertical finger movements (i.e. you could increase the vertical threshold since it's currently much smaller than the horizontal one), and
2. lock the scrolling direction to the first movement after the tap + hold so that horizontal scrolling can not be overridden by vertical finger movement and vice versa.

I hope this detailed breakdown of the issue helps with understanding and fixing it, because although it's not a major problem, fixing it would be a major QoL improvement.

Thanks for reading, Markus, and thanks for all your hard work and dedication to this free app.

**Comment by markusfisch** [comment]
Well, I can understand that this is a bit annoying 😬 This could really use some improvement.

The thresholds and the whole behaviour is the default of Android's [EditText](https://developer.android.com/reference/android/widget/EditText) control. The app doesn't change anything here, what is probably questionable given the long lines, of course.
